version: "3.8"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - db
    ports:
      - 80:80
  db:
      image: mysql:8.0
      container_name: appsDB
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
       - 8000:3306
      environment:
        MYSQL_ROOT_PASSWORD: hello123
        MYSQL_DATABASE: docker
        MYSQL_USER: project
        MYSQL_PASSWORD: hello1234
      volumes:
       - ./database:/docker-entrypoint-initdb.d
       - persistent:/var/lib/mysql
  app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - 8080:80
      environment:
        PMA_HOST: db
volumes:
      persistent:
