FROM phoronix/pts
MAINTAINER Gadagoju Abhilash <abhilash.gadagoju@gmail.com>
RUN apt-get update \
    && apt-get -y install \
          build-essential autoconf-doc unzip perl perl-base perl-modules libsdl-perl gcc libexpat1-dev \
          libperl-dev libpcre3-dev mesa-utils zlib1g-dev libpng-dev sqlite